/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package poc.gradle.app;

import java.math.BigDecimal;

import poc.gradle.domain.Product;

public class App {
	public static void main(String[] args) {

		Product product = new Product();
		product.setName("Gradle");
		product.setDescription("Best product");
		product.setPrice(BigDecimal.ONE);
		System.out.println(product.toString());
	}
}
