/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package poc.gradle.app;

import poc.gradle.list.LinkedList;

import static poc.gradle.utilities.StringUtils.join;
import static poc.gradle.utilities.StringUtils.split;
import static poc.gradle.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}

